name = "SMLMView"
uuid = "83077460-0282-453d-8507-e85496fba1c9"
version = "0.1.0-DEV"
authors = ["klidke@unm.edu"]

[deps]
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
WGLMakie = "276b4fcb-3e11-5398-bf8b-a0c2d153d008"

[compat]
Observables = "0.5"
Printf = "1.11.0"
Statistics = "1"
WGLMakie = "0.13.6"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
